name: US Gongsi Summary

on:
  schedule:
    - cron: '0 0 * * *' # 한국 시간 아침 9시
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install telethon requests
      - name: Run US Bot
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_SESSION_STRING: ${{ secrets.TG_SESSION_STRING }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        run: python run_us_bot.py
